# Generated by Django 5.1.2 on 2024-11-06 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=100)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.departments')),
            ],
        ),
    ]
